version: '3'

services:
  server:
#    image: jetbrains/teamcity-server:latest
    image: jetbrains/teamcity-server:latest
    container_name: server
    networks:
      - web
      - default
    volumes:
      - ./data:/data/teamcity_server/datadir
      - ./logs:/opt/teamcity/logs
    hostname: ${VIRTUAL_HOST}
    ports:
      - "8111"
    depends_on:
      - postgres
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.rule=Host(`whoami.$MY_DOMAIN`)"
      - "traefik.http.routers.whoami.tls.certresolver=lets-encr"

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  agent:
    build: ./agents/python-node-yarn
    env_file: .env
    depends_on:
      - redis
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  postgres:
    image: postgres
    restart: always
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
      - "./pg_backup:/backups"
    env_file: .env
    ports:
      - "5432"
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:3.2
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  traefik:
    image: traefik:1.7-alpine
    restart: on-failure
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  web:
    external: true