version: '3'

services:
  server:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    container_name: server
    networks:
      - web
      - default
    volumes:
      - ./data:/data/teamcity_server/datadir:rw
      - ./logs:/opt/teamcity/logs:rw
    hostname: ${VIRTUAL_HOST}
    ports:
      - "8111"
    depends_on:
      - postgres
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=server"
      - "traefik.frontend.rule=Host:${VIRTUAL_HOST}"
      - "traefik.docker.network=web"
      - "traefik.port=8111"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    labels:
      - "traefik.enable=false"
    volumes:
      - ./agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - redis

  teamcity-agent-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    privileged: true
    labels:
      - "traefik.enable=false"
    volumes:
      - ./agents/agent-2/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - redis

  postgres:
    image: postgres:latest
    restart: always
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
      - "./pg_backup:/backups"
    env_file: .env
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  redis:
    image: redis:3.2
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  traefik:
    image: traefik:1.7-alpine
    restart: on-failure
    command:
      - --logLevel=ERROR
      - --docker
      - --docker.watch=true
      - --docker.exposedByDefault=false
#      - --docker.domain=${VIRTUAL_HOST}
      - --defaultEntryPoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --acme=true
      - --acme.domains=${LETSENCRYPT_HOST}
      - --acme.email=${LETSENCRYPT_EMAIL}
      - --acme.storage=acme.json
      - --acme.OnHostRule=false
      - --acme.onDemand=false
      - --acme.entryPoint=https
      - --acme.httpChallenge
      - --acme.httpChallenge.entryPoint=http
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  web:
    external: true