version: "2.1"
services:
  server:
    image: jetbrains/teamcity-server:latest
    ports:
      - "8111:8111"
    volumes:
      - datadir:/data/teamcity_server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
  agent:
    image: jetbrains/teamcity-agent:latest
    volumes:
      - agents:/data/agent-1/conf
      - agents:/data/agent-2/conf
    environment:
      - SERVER_URL=http://server:8111