version: '3.4'


# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent

services:
  db:
    image: postgres:latest
    container_name: postgres
    volumes:
      - "./pg_data:/var/lib/postgresql/data"
      - "./pg_backup:/backups"
    restart: always
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}
    container_name: teamcity
    hostname: ${VIRTUAL_HOST}
    networks:
      - default
      - web
    ports:
        - "8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db
    restart: unless-stopped
    env_file: .env
    healthcheck:
      test: curl --fail http://localhost:8111 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
    environment:
      TEAMCITY_SERVER_MEM_OPTS: "-Xmx512m"

  redis:
    image: redis:3.2
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    container_name: teamcity-agent-1
    privileged: true
    env_file: .env
    volumes:
      - ./agents/agent-1/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - redis
    healthcheck:
      test: curl --fail http://localhost:9090 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
    networks:
      - web
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  teamcity-agent-2:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    container_name: teamcity-agent-2
    privileged: true
    env_file: .env
    volumes:
      - ./agents/agent-2/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - redis
    healthcheck:
      test: curl --fail http://localhost:9090 || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
      start_period: 20s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.23
    container_name: cicd-nginx
    restart: unless-stopped
    networks:
      - web
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ${NGINX_CONF_FILE}:/etc/nginx/conf.d/default.conf:ro
      - ${NGINX_SSL_CERTS}:/etc/ssl
      - ${NGINX_LOGS}:/var/log/nginx
networks:
  web:
    external: true
